<?xml version="1.0"?>

<!-- DTD for the XMLBIF 0.3 format -->
<!DOCTYPE BIF [
    <!ELEMENT BIF ( NETWORK )*>
        <!ATTLIST BIF VERSION CDATA #REQUIRED PRM CDATA #IMPLIED>
    <!ELEMENT NETWORK ( NAME, ( PROPERTY | PRM_CLASS | VARIABLE | DEFINITION )* )>
    <!ELEMENT PRM_CLASS (PRM_CLASSNAME, PRM_ATTRIBUTESET)>
    <!ELEMENT PRM_CLASSNAME (#PCDATA)>
    <!ELEMENT PRM_ATTRIBUTESET (PRM_PKEY+, PRM_RKEY*, PRM_ATTRIBUTE*)>
    <!ELEMENT PRM_PKEY (#PCDATA)>
    <!ELEMENT PRM_RKEY (#PCDATA)>
    <!ELEMENT PRM_ATTRIBUTE (#PCDATA)>
    <!ELEMENT NAME (#PCDATA)>
    <!ELEMENT VARIABLE ( NAME, ( OUTCOME | PROPERTY )* ) >
        <!ATTLIST VARIABLE TYPE (nature|decision|utility) "nature">
    <!ELEMENT OUTCOME (#PCDATA)>
    <!ELEMENT DEFINITION ( FOR | GIVEN | TABLE | PROPERTY )* >
    <!ELEMENT FOR (#PCDATA)>
    <!ELEMENT GIVEN (#PCDATA)>
    <!ELEMENT TABLE (#PCDATA)>
    <!ELEMENT PROPERTY (#PCDATA)>
]>

<BIF VERSION="0.3">
  <NETWORK>
    <NAME>Unknown</NAME>
      <!-- Variables -->
      <VARIABLE TYPE="nature">
         <NAME>LowLLapse</NAME>
        <OUTCOME>CloseToDryAd</OUTCOME>
        <OUTCOME>Steep</OUTCOME>
        <OUTCOME>ModerateOrLe</OUTCOME>
        <OUTCOME>Stable</OUTCOME>
        <PROPERTY> position = (463, 136) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>AMInsWliScen</NAME>
        <OUTCOME>LessUnstable</OUTCOME>
        <OUTCOME>Average</OUTCOME>
        <OUTCOME>MoreUnstable</OUTCOME>
        <PROPERTY> position = (494, 109) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>AMDewptCalPl</NAME>
        <OUTCOME>Instability</OUTCOME>
        <OUTCOME>Neutral</OUTCOME>
        <OUTCOME>Stability</OUTCOME>
        <PROPERTY> position = (289, 90) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>R5Fcst</NAME>
        <OUTCOME>XNIL</OUTCOME>
        <OUTCOME>SIG</OUTCOME>
        <OUTCOME>SVR</OUTCOME>
        <PROPERTY> position = (330, 107) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>Date</NAME>
        <OUTCOME>May15_Jun14</OUTCOME>
        <OUTCOME>Jun15_Jul1</OUTCOME>
        <OUTCOME>Jul2_Jul15</OUTCOME>
        <OUTCOME>Jul16_Aug10</OUTCOME>
        <OUTCOME>Aug11_Aug20</OUTCOME>
        <OUTCOME>Aug20_Sep15</OUTCOME>
        <PROPERTY> position = (318, 73) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>CapChange</NAME>
        <OUTCOME>Decreasing</OUTCOME>
        <OUTCOME>LittleChange</OUTCOME>
        <OUTCOME>Increasing</OUTCOME>
        <PROPERTY> position = (195, 266) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>CldShadeOth</NAME>
        <OUTCOME>Cloudy</OUTCOME>
        <OUTCOME>PC</OUTCOME>
        <OUTCOME>Clear</OUTCOME>
        <PROPERTY> position = (421, 139) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>N0_7muVerMo</NAME>
        <OUTCOME>StrongUp</OUTCOME>
        <OUTCOME>WeakUp</OUTCOME>
        <OUTCOME>Neutral</OUTCOME>
        <OUTCOME>Down</OUTCOME>
        <PROPERTY> position = (243, 314) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>TempDis</NAME>
        <OUTCOME>QStationary</OUTCOME>
        <OUTCOME>Moving</OUTCOME>
        <OUTCOME>None</OUTCOME>
        <OUTCOME>Other</OUTCOME>
        <PROPERTY> position = (277, 122) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>ScenRelAMIns</NAME>
        <OUTCOME>ABI</OUTCOME>
        <OUTCOME>CDEJ</OUTCOME>
        <OUTCOME>F</OUTCOME>
        <OUTCOME>G</OUTCOME>
        <OUTCOME>H</OUTCOME>
        <OUTCOME>K</OUTCOME>
        <PROPERTY> position = (122, 325) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>LLIW</NAME>
        <OUTCOME>Unfavorable</OUTCOME>
        <OUTCOME>Weak</OUTCOME>
        <OUTCOME>Moderate</OUTCOME>
        <OUTCOME>Strong</OUTCOME>
        <PROPERTY> position = (306, 121) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>CurPropConv</NAME>
        <OUTCOME>None</OUTCOME>
        <OUTCOME>Slight</OUTCOME>
        <OUTCOME>Moderate</OUTCOME>
        <OUTCOME>Strong</OUTCOME>
        <PROPERTY> position = (48, 336) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>MvmtFeatures</NAME>
        <OUTCOME>StrongFront</OUTCOME>
        <OUTCOME>MarkedUpper</OUTCOME>
        <OUTCOME>OtherRapid</OUTCOME>
        <OUTCOME>NoMajor</OUTCOME>
        <PROPERTY> position = (287, 48) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>QGVertMotion</NAME>
        <OUTCOME>StrongUp</OUTCOME>
        <OUTCOME>WeakUp</OUTCOME>
        <OUTCOME>Neutral</OUTCOME>
        <OUTCOME>Down</OUTCOME>
        <PROPERTY> position = (398, 193) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>SatContMoist</NAME>
        <OUTCOME>VeryWet</OUTCOME>
        <OUTCOME>Wet</OUTCOME>
        <OUTCOME>Neutral</OUTCOME>
        <OUTCOME>Dry</OUTCOME>
        <PROPERTY> position = (391, 40) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>PlainsFcst</NAME>
        <OUTCOME>XNIL</OUTCOME>
        <OUTCOME>SIG</OUTCOME>
        <OUTCOME>SVR</OUTCOME>
        <PROPERTY> position = (91, 250) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>LatestCIN</NAME>
        <OUTCOME>None</OUTCOME>
        <OUTCOME>PartInhibit</OUTCOME>
        <OUTCOME>Stifling</OUTCOME>
        <OUTCOME>TotalInhibit</OUTCOME>
        <PROPERTY> position = (250, 98) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>MountainFcst</NAME>
        <OUTCOME>XNIL</OUTCOME>
        <OUTCOME>SIG</OUTCOME>
        <OUTCOME>SVR</OUTCOME>
        <PROPERTY> position = (202, 115) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>CombClouds</NAME>
        <OUTCOME>Cloudy</OUTCOME>
        <OUTCOME>PC</OUTCOME>
        <OUTCOME>Clear</OUTCOME>
        <PROPERTY> position = (123, 113) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>WindFieldPln</NAME>
        <OUTCOME>LV</OUTCOME>
        <OUTCOME>DenvCyclone</OUTCOME>
        <OUTCOME>LongAnticyc</OUTCOME>
        <OUTCOME>E_NE</OUTCOME>
        <OUTCOME>SEQuad</OUTCOME>
        <OUTCOME>WidespdDnsl</OUTCOME>
        <PROPERTY> position = (302, 230) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>MeanRH</NAME>
        <OUTCOME>VeryMoist</OUTCOME>
        <OUTCOME>Average</OUTCOME>
        <OUTCOME>Dry</OUTCOME>
        <PROPERTY> position = (64, 280) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>OutflowFrMt</NAME>
        <OUTCOME>None</OUTCOME>
        <OUTCOME>Weak</OUTCOME>
        <OUTCOME>Strong</OUTCOME>
        <PROPERTY> position = (197, 308) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>ScnRelPlFcst</NAME>
        <OUTCOME>A</OUTCOME>
        <OUTCOME>B</OUTCOME>
        <OUTCOME>C</OUTCOME>
        <OUTCOME>D</OUTCOME>
        <OUTCOME>E</OUTCOME>
        <OUTCOME>F</OUTCOME>
        <OUTCOME>G</OUTCOME>
        <OUTCOME>H</OUTCOME>
        <OUTCOME>I</OUTCOME>
        <OUTCOME>J</OUTCOME>
        <OUTCOME>K</OUTCOME>
        <PROPERTY> position = (62, 14) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>CompPlFcst</NAME>
        <OUTCOME>IncCapDecIns</OUTCOME>
        <OUTCOME>LittleChange</OUTCOME>
        <OUTCOME>DecCapIncIns</OUTCOME>
        <PROPERTY> position = (418, 69) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>InsChange</NAME>
        <OUTCOME>Decreasing</OUTCOME>
        <OUTCOME>LittleChange</OUTCOME>
        <OUTCOME>Increasing</OUTCOME>
        <PROPERTY> position = (0, 158) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>LoLevMoistAd</NAME>
        <OUTCOME>StrongPos</OUTCOME>
        <OUTCOME>WeakPos</OUTCOME>
        <OUTCOME>Neutral</OUTCOME>
        <OUTCOME>Negative</OUTCOME>
        <PROPERTY> position = (30, 109) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>IRCloudCover</NAME>
        <OUTCOME>Cloudy</OUTCOME>
        <OUTCOME>PC</OUTCOME>
        <OUTCOME>Clear</OUTCOME>
        <PROPERTY> position = (451, 267) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>AMInstabMt</NAME>
        <OUTCOME>None</OUTCOME>
        <OUTCOME>Weak</OUTCOME>
        <OUTCOME>Strong</OUTCOME>
        <PROPERTY> position = (90, 137) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>N34StarFcst</NAME>
        <OUTCOME>XNIL</OUTCOME>
        <OUTCOME>SIG</OUTCOME>
        <OUTCOME>SVR</OUTCOME>
        <PROPERTY> position = (240, 209) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>AreaMeso_ALS</NAME>
        <OUTCOME>StrongUp</OUTCOME>
        <OUTCOME>WeakUp</OUTCOME>
        <OUTCOME>Neutral</OUTCOME>
        <OUTCOME>Down</OUTCOME>
        <PROPERTY> position = (163, 281) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>AMCINInScen</NAME>
        <OUTCOME>LessThanAve</OUTCOME>
        <OUTCOME>Average</OUTCOME>
        <OUTCOME>MoreThanAve</OUTCOME>
        <PROPERTY> position = (266, 310) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>Boundaries</NAME>
        <OUTCOME>None</OUTCOME>
        <OUTCOME>Weak</OUTCOME>
        <OUTCOME>Strong</OUTCOME>
        <PROPERTY> position = (206, 360) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>Scenario</NAME>
        <OUTCOME>A</OUTCOME>
        <OUTCOME>B</OUTCOME>
        <OUTCOME>C</OUTCOME>
        <OUTCOME>D</OUTCOME>
        <OUTCOME>E</OUTCOME>
        <OUTCOME>F</OUTCOME>
        <OUTCOME>G</OUTCOME>
        <OUTCOME>H</OUTCOME>
        <OUTCOME>I</OUTCOME>
        <OUTCOME>J</OUTCOME>
        <OUTCOME>K</OUTCOME>
        <PROPERTY> position = (206, 368) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>InsSclInScen</NAME>
        <OUTCOME>LessUnstable</OUTCOME>
        <OUTCOME>Average</OUTCOME>
        <OUTCOME>MoreUnstable</OUTCOME>
        <PROPERTY> position = (59, 22) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>SfcWndShfDis</NAME>
        <OUTCOME>DenvCyclone</OUTCOME>
        <OUTCOME>E_W_N</OUTCOME>
        <OUTCOME>E_W_S</OUTCOME>
        <OUTCOME>MovingFtorOt</OUTCOME>
        <OUTCOME>DryLine</OUTCOME>
        <OUTCOME>None</OUTCOME>
        <OUTCOME>Other</OUTCOME>
        <PROPERTY> position = (209, 176) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>RHRatio</NAME>
        <OUTCOME>MoistMDryL</OUTCOME>
        <OUTCOME>DryMMoistL</OUTCOME>
        <OUTCOME>Other</OUTCOME>
        <PROPERTY> position = (221, 214) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>MorningBound</NAME>
        <OUTCOME>None</OUTCOME>
        <OUTCOME>Weak</OUTCOME>
        <OUTCOME>Strong</OUTCOME>
        <PROPERTY> position = (293, 204) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>ScenRelAMCIN</NAME>
        <OUTCOME>AB</OUTCOME>
        <OUTCOME>CThruK</OUTCOME>
        <PROPERTY> position = (249, 99) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>WindFieldMt</NAME>
        <OUTCOME>Westerly</OUTCOME>
        <OUTCOME>LVorOther</OUTCOME>
        <PROPERTY> position = (8, 186) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>SynForcng</NAME>
        <OUTCOME>SigNegative</OUTCOME>
        <OUTCOME>NegToPos</OUTCOME>
        <OUTCOME>SigPositive</OUTCOME>
        <OUTCOME>PosToNeg</OUTCOME>
        <OUTCOME>LittleChange</OUTCOME>
        <PROPERTY> position = (309, 302) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>CapInScen</NAME>
        <OUTCOME>LessThanAve</OUTCOME>
        <OUTCOME>Average</OUTCOME>
        <OUTCOME>MoreThanAve</OUTCOME>
        <PROPERTY> position = (314, 247) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>MorningCIN</NAME>
        <OUTCOME>None</OUTCOME>
        <OUTCOME>PartInhibit</OUTCOME>
        <OUTCOME>Stifling</OUTCOME>
        <OUTCOME>TotalInhibit</OUTCOME>
        <PROPERTY> position = (40, 131) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>InsInMt</NAME>
        <OUTCOME>None</OUTCOME>
        <OUTCOME>Weak</OUTCOME>
        <OUTCOME>Strong</OUTCOME>
        <PROPERTY> position = (455, 8) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>LIfr12ZDENSd</NAME>
        <OUTCOME>LIGt0</OUTCOME>
        <OUTCOME>N1GtLIGt_4</OUTCOME>
        <OUTCOME>N5GtLIGt_8</OUTCOME>
        <OUTCOME>LILt_8</OUTCOME>
        <PROPERTY> position = (356, 74) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>MidLLapse</NAME>
        <OUTCOME>CloseToDryAd</OUTCOME>
        <OUTCOME>Steep</OUTCOME>
        <OUTCOME>ModerateOrLe</OUTCOME>
        <PROPERTY> position = (314, 296) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>WndHodograph</NAME>
        <OUTCOME>DCVZFavor</OUTCOME>
        <OUTCOME>StrongWest</OUTCOME>
        <OUTCOME>Westerly</OUTCOME>
        <OUTCOME>Other</OUTCOME>
        <PROPERTY> position = (94, 89) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>CldShadeConv</NAME>
        <OUTCOME>None</OUTCOME>
        <OUTCOME>Some</OUTCOME>
        <OUTCOME>Marked</OUTCOME>
        <PROPERTY> position = (44, 161) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>SubjVertMo</NAME>
        <OUTCOME>StronUp</OUTCOME>
        <OUTCOME>WeakUp</OUTCOME>
        <OUTCOME>Neutral</OUTCOME>
        <OUTCOME>Down</OUTCOME>
        <PROPERTY> position = (374, 150) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>CombMoisture</NAME>
        <OUTCOME>VeryWet</OUTCOME>
        <OUTCOME>Wet</OUTCOME>
        <OUTCOME>Neutral</OUTCOME>
        <OUTCOME>Dry</OUTCOME>
        <PROPERTY> position = (192, 134) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>ScenRel3_4</NAME>
        <OUTCOME>ACEFK</OUTCOME>
        <OUTCOME>B</OUTCOME>
        <OUTCOME>D</OUTCOME>
        <OUTCOME>GJ</OUTCOME>
        <OUTCOME>HI</OUTCOME>
        <PROPERTY> position = (251, 169) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>VISCloudCov</NAME>
        <OUTCOME>Cloudy</OUTCOME>
        <OUTCOME>PC</OUTCOME>
        <OUTCOME>Clear</OUTCOME>
        <PROPERTY> position = (247, 92) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>RaoContMoist</NAME>
        <OUTCOME>VeryWet</OUTCOME>
        <OUTCOME>Wet</OUTCOME>
        <OUTCOME>Neutral</OUTCOME>
        <OUTCOME>Dry</OUTCOME>
        <PROPERTY> position = (399, 0) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>WindAloft</NAME>
        <OUTCOME>LV</OUTCOME>
        <OUTCOME>SWQuad</OUTCOME>
        <OUTCOME>NWQuad</OUTCOME>
        <OUTCOME>AllElse</OUTCOME>
        <PROPERTY> position = (273, 376) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>AreaMoDryAir</NAME>
        <OUTCOME>VeryWet</OUTCOME>
        <OUTCOME>Wet</OUTCOME>
        <OUTCOME>Neutral</OUTCOME>
        <OUTCOME>Dry</OUTCOME>
        <PROPERTY> position = (202, 237) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>CombVerMo</NAME>
        <OUTCOME>StrongUp</OUTCOME>
        <OUTCOME>WeakUp</OUTCOME>
        <OUTCOME>Neutral</OUTCOME>
        <OUTCOME>Down</OUTCOME>
        <PROPERTY> position = (72, 339) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>Dewpoints</NAME>
        <OUTCOME>LowEvrywhere</OUTCOME>
        <OUTCOME>LowAtStation</OUTCOME>
        <OUTCOME>LowSHighN</OUTCOME>
        <OUTCOME>LowNHighS</OUTCOME>
        <OUTCOME>LowMtsHighPl</OUTCOME>
        <OUTCOME>HighEvrywher</OUTCOME>
        <OUTCOME>Other</OUTCOME>
        <PROPERTY> position = (104, 74) </PROPERTY>
      </VARIABLE>
      <!-- Probability Distributions -->
      <DEFINITION>
        <FOR>LowLLapse</FOR>
        <GIVEN>Scenario</GIVEN>
        <TABLE>0.04 0.07 0.35 0.4 0.45 0.01 0.78 0.0 0.22 0.13 0.09 0.25 0.31 0.47 0.4 0.35 0.35 0.19 0.02 0.4 0.4 0.4 0.35 0.31 0.14 0.13 0.15 0.45 0.03 0.33 0.3 0.35 0.33 0.36 0.31 0.04 0.07 0.05 0.19 0.0 0.65 0.08 0.12 0.18</TABLE>
      </DEFINITION>
      <DEFINITION>
        <FOR>AMInsWliScen</FOR>
        <GIVEN>ScenRelAMIns</GIVEN>
        <GIVEN>LIfr12ZDENSd</GIVEN>
        <GIVEN>AMDewptCalPl</GIVEN>
        <TABLE>0.6 0.85 0.95 0.3 0.5 0.75 0.06 0.2 0.5 0.01 0.05 0.35 0.4 0.7 0.9 0.15 0.25 0.6 0.03 0.2 0.45 0.01 0.05 0.25 0.35 0.55 0.85 0.07 0.2 0.5 0.0 0.05 0.25 0.0 0.0 0.04 0.3 0.5 0.75 0.15 0.2 0.15 0.07 0.13 0.1 0.02 0.04 0.07 0.35 0.4 0.58 0.1 0.15 0.4 0.02 0.05 0.15 0.01 0.03 0.08 0.3 0.4 0.5 0.1 0.25 0.3 0.05 0.1 0.15 0.02 0.04 0.1 0.3 0.13 0.04 0.3 0.3 0.2 0.21 0.4 0.4 0.04 0.2 0.35 0.3 0.2 0.08 0.3 0.5 0.3 0.17 0.3 0.4 0.04 0.18 0.4 0.35 0.4 0.13 0.38 0.6 0.43 0.05 0.35 0.5 0.02 0.05 0.16 0.4 0.3 0.2 0.35 0.6 0.7 0.23 0.47 0.75 0.18 0.26 0.3 0.45 0.5 0.4 0.25 0.45 0.45 0.18 0.25 0.35 0.09 0.17 0.32 0.55 0.5 0.43 0.35 0.5 0.5 0.22 0.35 0.35 0.1 0.16 0.25 0.1 0.02 0.01 0.4 0.2 0.05 0.73 0.4 0.1 0.95 0.75 0.3 0.3 0.1 0.02 0.55 0.25 0.1 0.8 0.5 0.15 0.95 0.77 0.35 0.3 0.05 0.02 0.55 0.2 0.07 0.95 0.6 0.25 0.98 0.95 0.8 0.3 0.2 0.05 0.5 0.2 0.15 0.7 0.4 0.15 0.8 0.7 0.63 0.2 0.1 0.02 0.65 0.4 0.15 0.8 0.7 0.5 0.9 0.8 0.6 0.15 0.1 0.07 0.55 0.25 0.2 0.73 0.55 0.5 0.88 0.8 0.65</TABLE>
      </DEFINITION>
      <DEFINITION>
        <FOR>AMDewptCalPl</FOR>
        <TABLE>0.3 0.25 0.45</TABLE>
      </DEFINITION>
      <DEFINITION>
        <FOR>R5Fcst</FOR>
        <GIVEN>MountainFcst</GIVEN>
        <GIVEN>N34StarFcst</GIVEN>
        <TABLE>1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 1.0 1.0 1.0</TABLE>
      </DEFINITION>
      <DEFINITION>
        <FOR>Date</FOR>
        <TABLE>0.254098 0.131148 0.106557 0.213115 0.07377 0.221312</TABLE>
      </DEFINITION>
      <DEFINITION>
        <FOR>CapChange</FOR>
        <GIVEN>CompPlFcst</GIVEN>
        <TABLE>0.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0</TABLE>
      </DEFINITION>
      <DEFINITION>
        <FOR>CldShadeOth</FOR>
        <GIVEN>AreaMoDryAir</GIVEN>
        <GIVEN>AreaMeso_ALS</GIVEN>
        <GIVEN>CombClouds</GIVEN>
        <TABLE>1.0 0.85 0.25 0.95 0.4 0.05 0.93 0.2 0.01 0.74 0.0 0.0 0.92 0.7 0.15 0.9 0.25 0.01 0.8 0.01 0.0 0.65 0.0 0.0 0.88 0.4 0.1 0.85 0.15 0.0 0.8 0.03 0.0 0.5 0.01 0.0 0.85 0.55 0.1 0.6 0.01 0.0 0.78 0.01 0.0 0.42 0.05 0.0 0.0 0.15 0.35 0.05 0.55 0.45 0.07 0.78 0.29 0.25 0.5 0.1 0.08 0.29 0.4 0.09 0.6 0.3 0.2 0.89 0.1 0.34 0.4 0.02 0.12 0.5 0.4 0.15 0.75 0.2 0.18 0.85 0.05 0.48 0.74 0.01 0.14 0.43 0.25 0.39 0.9 0.15 0.2 0.74 0.04 0.55 0.65 0.0 0.0 0.0 0.4 0.0 0.05 0.5 0.0 0.02 0.7 0.01 0.5 0.9 0.0 0.01 0.45 0.01 0.15 0.69 0.0 0.1 0.9 0.01 0.6 0.98 0.0 0.1 0.5 0.0 0.1 0.8 0.02 0.12 0.95 0.02 0.25 0.99 0.01 0.02 0.65 0.01 0.09 0.85 0.02 0.25 0.96 0.03 0.3 1.0</TABLE>
      </DEFINITION>
      <DEFINITION>
        <FOR>N0_7muVerMo</FOR>
        <TABLE>0.25 0.25 0.25 0.25</TABLE>
      </DEFINITION>
      <DEFINITION>
        <FOR>TempDis</FOR>
        <GIVEN>Scenario</GIVEN>
        <TABLE>0.13 0.15 0.12 0.1 0.04 0.05 0.03 0.05 0.8 0.1 0.2 0.15 0.15 0.1 0.15 0.04 0.12 0.03 0.4 0.19 0.05 0.3 0.1 0.25 0.35 0.4 0.82 0.75 0.84 0.5 0.0 0.4 0.3 0.62 0.45 0.43 0.35 0.1 0.08 0.1 0.05 0.01 0.45 0.2</TABLE>
      </DEFINITION>
      <DEFINITION>
        <FOR>ScenRelAMIns</FOR>
        <GIVEN>Scenario</GIVEN>
        <TABLE>1.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 1.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0</TABLE>
      </DEFINITION>
      <DEFINITION>
        <FOR>LLIW</FOR>
        <TABLE>0.12 0.32 0.38 0.18</TABLE>
      </DEFINITION>
      <DEFINITION>
        <FOR>CurPropConv</FOR>
        <GIVEN>LatestCIN</GIVEN>
        <GIVEN>LLIW</GIVEN>
        <TABLE>0.7 0.1 0.01 0.0 0.9 0.65 0.25 0.01 0.95 0.75 0.4 0.2 1.0 0.95 0.75 0.5 0.28 0.5 0.14 0.02 0.09 0.25 0.35 0.15 0.05 0.23 0.4 0.3 0.0 0.05 0.2 0.35 0.02 0.3 0.35 0.18 0.01 0.09 0.3 0.33 0.0 0.02 0.18 0.35 0.0 0.0 0.05 0.1 0.0 0.1 0.5 0.8 0.0 0.01 0.1 0.51 0.0 0.0 0.02 0.15 0.0 0.0 0.0 0.05</TABLE>
      </DEFINITION>
      <DEFINITION>
        <FOR>MvmtFeatures</FOR>
        <GIVEN>Scenario</GIVEN>
        <TABLE>0.25 0.05 0.1 0.18 0.02 0.05 0.1 0.0 0.2 0.04 0.5 0.55 0.1 0.3 0.38 0.02 0.07 0.25 0.6 0.1 0.0 0.35 0.2 0.1 0.3 0.34 0.26 0.05 0.15 0.1 0.2 0.04 0.09 0.0 0.75 0.3 0.1 0.7 0.83 0.5 0.3 0.5 0.92 0.06</TABLE>
      </DEFINITION>
      <DEFINITION>
        <FOR>QGVertMotion</FOR>
        <TABLE>0.15 0.15 0.5 0.2</TABLE>
      </DEFINITION>
      <DEFINITION>
        <FOR>SatContMoist</FOR>
        <TABLE>0.15 0.2 0.4 0.25</TABLE>
      </DEFINITION>
      <DEFINITION>
        <FOR>PlainsFcst</FOR>
        <GIVEN>CurPropConv</GIVEN>
        <GIVEN>InsSclInScen</GIVEN>
        <GIVEN>CapInScen</GIVEN>
        <GIVEN>ScnRelPlFcst</GIVEN>
        <TABLE>0.75 0.75 0.9 0.9 0.88 0.92 0.85 1.0 0.9 0.9 0.95 0.75 0.65 0.9 0.91 0.85 0.9 0.84 0.99 0.88 0.92 0.96 0.75 0.75 0.95 0.93 0.92 0.87 0.9 0.98 0.92 0.95 0.97 0.5 0.6 0.8 0.85 0.85 0.88 0.8 0.92 0.8 0.75 0.9 0.35 0.55 0.82 0.82 0.75 0.88 0.75 0.9 0.7 0.8 0.9 0.5 0.6 0.85 0.85 0.75 0.85 0.75 0.94 0.65 0.83 0.93 0.35 0.45 0.8 0.72 0.78 0.86 0.65 0.85 0.65 0.72 0.85 0.25 0.45 0.65 0.55 0.55 0.81 0.6 0.8 0.6 0.75 0.88 0.4 0.45 0.75 0.65 0.52 0.82 0.65 0.85 0.5 0.77 0.9 0.7 0.6 0.82 0.85 0.82 0.85 0.8 0.97 0.88 0.86 0.88 0.65 0.58 0.8 0.85 0.8 0.83 0.77 0.93 0.85 0.85 0.9 0.6 0.65 0.9 0.85 0.82 0.8 0.8 0.91 0.85 0.9 0.93 0.3 0.55 0.7 0.75 0.62 0.85 0.75 0.82 0.6 0.68 0.82 0.28 0.48 0.7 0.7 0.6 0.82 0.63 0.8 0.5 0.7 0.8 0.4 0.5 0.72 0.65 0.55 0.78 0.55 0.85 0.45 0.73 0.85 0.3 0.4 0.65 0.6 0.6 0.83 0.45 0.7 0.55 0.6 0.72 0.22 0.35 0.45 0.45 0.48 0.72 0.43 0.68 0.35 0.6 0.74 0.27 0.35 0.55 0.45 0.42 0.74 0.45 0.77 0.3 0.68 0.75 0.5 0.45 0.75 0.75 0.72 0.78 0.66 0.88 0.7 0.78 0.8 0.45 0.45 0.7 0.72 0.7 0.75 0.62 0.85 0.75 0.76 0.8 0.35 0.45 0.75 0.7 0.6 0.72 0.6 0.8 0.75 0.75 0.88 0.2 0.4 0.7 0.65 0.5 0.74 0.6 0.67 0.35 0.6 0.75 0.23 0.38 0.58 0.55 0.53 0.73 0.35 0.65 0.3 0.6 0.68 0.3 0.35 0.55 0.5 0.4 0.7 0.35 0.6 0.35 0.62 0.7 0.25 0.3 0.45 0.5 0.4 0.72 0.25 0.57 0.25 0.48 0.6 0.19 0.25 0.35 0.35 0.35 0.65 0.22 0.45 0.25 0.48 0.58 0.15 0.25 0.4 0.3 0.25 0.6 0.18 0.47 0.25 0.5 0.5 0.4 0.35 0.6 0.6 0.55 0.69 0.54 0.75 0.55 0.7 0.7 0.35 0.35 0.55 0.55 0.5 0.65 0.38 0.7 0.65 0.67 0.7 0.2 0.3 0.55 0.5 0.45 0.6 0.28 0.65 0.63 0.62 0.8 0.16 0.3 0.45 0.52 0.35 0.65 0.48 0.58 0.25 0.5 0.65 0.18 0.3 0.45 0.45 0.35 0.62 0.2 0.52 0.23 0.47 0.55 0.23 0.25 0.4 0.4 0.3 0.57 0.15 0.5 0.25 0.5 0.55 0.18 0.2 0.3 0.4 0.25 0.63 0.15 0.4 0.2 0.3 0.5 0.15 0.18 0.25 0.25 0.25 0.58 0.13 0.3 0.22 0.35 0.5 0.1 0.2 0.2 0.23 0.15 0.5 0.1 0.28 0.2 0.3 0.38 0.2 0.2 0.08 0.06 0.1 0.08 0.13 0.0 0.08 0.08 0.04 0.2 0.3 0.08 0.05 0.13 0.1 0.12 0.01 0.1 0.06 0.03 0.2 0.2 0.04 0.04 0.06 0.13 0.06 0.02 0.06 0.04 0.02 0.3 0.3 0.14 0.09 0.1 0.11 0.17 0.06 0.12 0.22 0.08 0.3 0.3 0.13 0.1 0.18 0.11 0.2 0.07 0.2 0.15 0.08 0.2 0.25 0.1 0.07 0.15 0.14 0.2 0.05 0.22 0.1 0.06 0.2 0.35 0.1 0.14 0.15 0.12 0.25 0.1 0.2 0.2 0.1 0.15 0.35 0.2 0.2 0.25 0.17 0.28 0.13 0.2 0.15 0.08 0.08 0.25 0.1 0.15 0.25 0.16 0.27 0.09 0.2 0.1 0.07 0.25 0.33 0.13 0.1 0.15 0.14 0.17 0.02 0.1 0.1 0.1 0.25 0.32 0.15 0.1 0.16 0.16 0.17 0.06 0.12 0.1 0.08 0.3 0.28 0.08 0.1 0.13 0.19 0.13 0.08 0.12 0.08 0.06 0.4 0.34 0.2 0.15 0.28 0.14 0.2 0.14 0.25 0.22 0.15 0.37 0.35 0.2 0.17 0.29 0.16 0.3 0.15 0.3 0.2 0.16 0.28 0.25 0.18 0.2 0.3 0.2 0.35 0.12 0.3 0.15 0.12 0.25 0.36 0.2 0.2 0.28 0.14 0.4 0.18 0.25 0.25 0.2 0.17 0.37 0.3 0.25 0.29 0.25 0.4 0.2 0.3 0.2 0.16 0.1 0.3 0.22 0.25 0.3 0.22 0.4 0.13 0.25 0.15 0.15 0.4 0.42 0.18 0.15 0.22 0.21 0.27 0.1 0.22 0.16 0.16 0.35 0.35 0.2 0.17 0.22 0.24 0.3 0.12 0.15 0.17 0.16 0.4 0.4 0.19 0.2 0.3 0.27 0.3 0.16 0.17 0.2 0.1 0.45 0.4 0.2 0.22 0.34 0.24 0.3 0.24 0.4 0.25 0.2 0.4 0.35 0.25 0.25 0.32 0.25 0.53 0.24 0.4 0.24 0.24 0.34 0.35 0.25 0.27 0.38 0.28 0.5 0.25 0.35 0.22 0.22 0.28 0.38 0.3 0.25 0.35 0.24 0.57 0.28 0.35 0.26 0.26 0.18 0.4 0.3 0.3 0.35 0.3 0.58 0.35 0.34 0.26 0.25 0.16 0.3 0.3 0.3 0.4 0.34 0.62 0.3 0.3 0.22 0.27 0.45 0.45 0.27 0.22 0.32 0.29 0.36 0.2 0.3 0.22 0.25 0.4 0.4 0.3 0.27 0.35 0.33 0.5 0.24 0.2 0.23 0.25 0.45 0.45 0.3 0.3 0.38 0.38 0.57 0.28 0.25 0.28 0.17 0.47 0.45 0.32 0.26 0.45 0.32 0.39 0.3 0.45 0.28 0.27 0.45 0.35 0.3 0.3 0.43 0.35 0.65 0.33 0.42 0.3 0.3 0.4 0.4 0.3 0.3 0.45 0.4 0.65 0.33 0.36 0.28 0.3 0.3 0.4 0.3 0.3 0.48 0.32 0.63 0.38 0.37 0.35 0.32 0.2 0.4 0.35 0.35 0.42 0.36 0.62 0.45 0.35 0.32 0.3 0.2 0.3 0.4 0.3 0.45 0.42 0.65 0.4 0.32 0.28 0.32 0.05 0.05 0.02 0.04 0.02 0.0 0.02 0.0 0.02 0.02 0.01 0.05 0.05 0.02 0.04 0.02 0.0 0.04 0.0 0.02 0.02 0.01 0.05 0.05 0.01 0.03 0.02 0.0 0.04 0.0 0.02 0.01 0.01 0.2 0.1 0.06 0.06 0.05 0.01 0.03 0.02 0.08 0.03 0.02 0.35 0.15 0.05 0.08 0.07 0.01 0.05 0.03 0.1 0.05 0.02 0.3 0.15 0.05 0.08 0.1 0.01 0.05 0.01 0.13 0.07 0.01 0.45 0.2 0.1 0.14 0.07 0.02 0.1 0.05 0.15 0.08 0.05 0.6 0.2 0.15 0.25 0.2 0.02 0.12 0.07 0.2 0.1 0.04 0.52 0.3 0.15 0.2 0.23 0.02 0.08 0.06 0.3 0.13 0.03 0.05 0.07 0.05 0.05 0.03 0.01 0.03 0.01 0.02 0.04 0.02 0.1 0.1 0.05 0.05 0.04 0.01 0.06 0.01 0.03 0.05 0.02 0.1 0.07 0.02 0.05 0.05 0.01 0.07 0.01 0.03 0.02 0.01 0.3 0.11 0.1 0.1 0.1 0.01 0.05 0.04 0.15 0.1 0.03 0.35 0.17 0.1 0.13 0.11 0.02 0.07 0.05 0.2 0.1 0.04 0.32 0.25 0.1 0.15 0.15 0.02 0.1 0.03 0.25 0.12 0.03 0.45 0.24 0.15 0.2 0.12 0.03 0.15 0.12 0.2 0.15 0.08 0.61 0.28 0.25 0.3 0.23 0.03 0.17 0.12 0.35 0.2 0.1 0.63 0.35 0.23 0.3 0.28 0.04 0.15 0.1 0.45 0.17 0.1 0.1 0.13 0.07 0.1 0.06 0.01 0.07 0.02 0.08 0.06 0.04 0.2 0.2 0.1 0.11 0.08 0.01 0.08 0.03 0.1 0.07 0.04 0.25 0.15 0.06 0.1 0.1 0.01 0.1 0.04 0.08 0.05 0.02 0.35 0.2 0.1 0.13 0.16 0.02 0.1 0.09 0.25 0.15 0.05 0.37 0.27 0.17 0.2 0.15 0.02 0.12 0.11 0.3 0.16 0.08 0.36 0.3 0.2 0.23 0.22 0.02 0.15 0.15 0.3 0.16 0.08 0.47 0.32 0.25 0.25 0.25 0.04 0.18 0.15 0.4 0.26 0.14 0.63 0.35 0.35 0.35 0.3 0.05 0.2 0.2 0.41 0.26 0.17 0.69 0.45 0.3 0.4 0.35 0.06 0.2 0.23 0.45 0.28 0.23 0.15 0.2 0.13 0.18 0.13 0.02 0.1 0.05 0.15 0.08 0.05 0.25 0.25 0.15 0.18 0.15 0.02 0.12 0.06 0.15 0.1 0.05 0.35 0.25 0.15 0.2 0.17 0.02 0.15 0.07 0.12 0.1 0.03 0.37 0.25 0.23 0.22 0.2 0.03 0.13 0.12 0.3 0.22 0.08 0.37 0.35 0.25 0.25 0.22 0.03 0.15 0.15 0.35 0.23 0.15 0.37 0.35 0.3 0.3 0.25 0.03 0.2 0.17 0.39 0.22 0.15 0.52 0.4 0.4 0.3 0.27 0.05 0.22 0.22 0.43 0.35 0.18 0.65 0.42 0.4 0.4 0.33 0.06 0.25 0.25 0.43 0.33 0.2 0.7 0.5 0.4 0.47 0.4 0.08 0.25 0.32 0.48 0.42 0.3</TABLE>
      </DEFINITION>
      <DEFINITION>
        <FOR>LatestCIN</FOR>
        <TABLE>0.4 0.4 0.15 0.05</TABLE>
      </DEFINITION>
      <DEFINITION>
        <FOR>MountainFcst</FOR>
        <GIVEN>InsInMt</GIVEN>
        <TABLE>1.0 0.48 0.2 0.0 0.5 0.5 0.0 0.02 0.3</TABLE>
      </DEFINITION>
      <DEFINITION>
        <FOR>CombClouds</FOR>
        <GIVEN>VISCloudCov</GIVEN>
        <GIVEN>IRCloudCover</GIVEN>
        <TABLE>0.95 0.85 0.8 0.45 0.1 0.05 0.1 0.02 0.0 0.04 0.13 0.1 0.52 0.8 0.45 0.4 0.28 0.02 0.01 0.02 0.1 0.03 0.1 0.5 0.5 0.7 0.98</TABLE>
      </DEFINITION>
      <DEFINITION>
        <FOR>WindFieldPln</FOR>
        <GIVEN>Scenario</GIVEN>
        <TABLE>0.05 0.08 0.1 0.1 0.43 0.6 0.25 0.04 0.2 0.6 0.1 0.6 0.6 0.0 0.15 0.1 0.07 0.01 0.02 0.3 0.08 0.05 0.02 0.02 0.75 0.2 0.15 0.01 0.3 0.04 0.05 0.07 0.1 0.1 0.1 0.0 0.05 0.06 0.12 0.01 0.8 0.37 0.03 0.05 0.23 0.2 0.0 0.3 0.06 0.2 0.03 0.1 0.07 0.2 0.2 0.0 0.0 0.15 0.2 0.2 0.0 0.4 0.0 0.01 0.02 0.5</TABLE>
      </DEFINITION>
      <DEFINITION>
        <FOR>MeanRH</FOR>
        <GIVEN>Scenario</GIVEN>
        <TABLE>0.33 0.4 0.05 0.1 0.05 1.0 0.0 0.4 0.2 0.05 0.2 0.5 0.4 0.45 0.5 0.65 0.0 0.07 0.55 0.45 0.55 0.4 0.17 0.2 0.5 0.4 0.3 0.0 0.93 0.05 0.35 0.4 0.4</TABLE>
      </DEFINITION>
      <DEFINITION>
        <FOR>OutflowFrMt</FOR>
        <GIVEN>InsInMt</GIVEN>
        <GIVEN>WndHodograph</GIVEN>
        <TABLE>1.0 1.0 1.0 1.0 0.5 0.15 0.35 0.8 0.05 0.01 0.1 0.6 0.0 0.0 0.0 0.0 0.4 0.4 0.6 0.19 0.45 0.15 0.25 0.3 0.0 0.0 0.0 0.0 0.1 0.45 0.05 0.01 0.5 0.84 0.65 0.1</TABLE>
      </DEFINITION>
      <DEFINITION>
        <FOR>ScnRelPlFcst</FOR>
        <GIVEN>Scenario</GIVEN>
        <TABLE>1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0</TABLE>
      </DEFINITION>
      <DEFINITION>
        <FOR>CompPlFcst</FOR>
        <GIVEN>Boundaries</GIVEN>
        <GIVEN>CldShadeConv</GIVEN>
        <GIVEN>AreaMeso_ALS</GIVEN>
        <GIVEN>CldShadeOth</GIVEN>