<?xml version="1.0"?>

<!-- DTD for the XMLBIF 0.3 format -->
<!DOCTYPE BIF [
    <!ELEMENT BIF ( NETWORK )*>
        <!ATTLIST BIF VERSION CDATA #REQUIRED PRM CDATA #IMPLIED>
    <!ELEMENT NETWORK ( NAME, ( PROPERTY | PRM_CLASS | VARIABLE | DEFINITION )* )>
    <!ELEMENT PRM_CLASS (PRM_CLASSNAME, PRM_ATTRIBUTESET)>
    <!ELEMENT PRM_CLASSNAME (#PCDATA)>
    <!ELEMENT PRM_ATTRIBUTESET (PRM_PKEY+, PRM_RKEY*, PRM_ATTRIBUTE*)>
    <!ELEMENT PRM_PKEY (#PCDATA)>
    <!ELEMENT PRM_RKEY (#PCDATA)>
    <!ELEMENT PRM_ATTRIBUTE (#PCDATA)>
    <!ELEMENT NAME (#PCDATA)>
    <!ELEMENT VARIABLE ( NAME, ( OUTCOME | PROPERTY )* ) >
        <!ATTLIST VARIABLE TYPE (nature|decision|utility) "nature">
    <!ELEMENT OUTCOME (#PCDATA)>
    <!ELEMENT DEFINITION ( FOR | GIVEN | TABLE | PROPERTY )* >
    <!ELEMENT FOR (#PCDATA)>
    <!ELEMENT GIVEN (#PCDATA)>
    <!ELEMENT TABLE (#PCDATA)>
    <!ELEMENT PROPERTY (#PCDATA)>
]>

<BIF VERSION="0.3">
  <NETWORK>
    <NAME>Untitled</NAME>
      <!-- Variables -->
      <VARIABLE TYPE="nature">
         <NAME>SC</NAME>
        <OUTCOME>0 Changed</OUTCOME>
        <OUTCOME>1 Changed</OUTCOME>
        <OUTCOME>2 Changed</OUTCOME>
        <PROPERTY> position = (288, 168) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>OH0</NAME>
        <OUTCOME>no</OUTCOME>
        <OUTCOME>1a</OUTCOME>
        <OUTCOME>2 cons</OUTCOME>
        <OUTCOME>2 s</OUTCOME>
        <OUTCOME>2 v</OUTCOME>
        <OUTCOME>fl</OUTCOME>
        <OUTCOME>st</OUTCOME>
        <OUTCOME>3 v</OUTCOME>
        <OUTCOME>stfl</OUTCOME>
        <PROPERTY> position = (143, 338) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>OH1</NAME>
        <OUTCOME>no</OUTCOME>
        <OUTCOME>1 a</OUTCOME>
        <OUTCOME>2 cons</OUTCOME>
        <OUTCOME>2 s</OUTCOME>
        <OUTCOME>2 v</OUTCOME>
        <OUTCOME>fl</OUTCOME>
        <OUTCOME>st</OUTCOME>
        <OUTCOME>3 v</OUTCOME>
        <OUTCOME>stfl</OUTCOME>
        <PROPERTY> position = (143, 225) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>OH2</NAME>
        <OUTCOME>no</OUTCOME>
        <OUTCOME>1 a</OUTCOME>
        <OUTCOME>2 v</OUTCOME>
        <OUTCOME>2 a</OUTCOME>
        <OUTCOME>fl</OUTCOME>
        <OUTCOME>st</OUTCOME>
        <OUTCOME>3 v</OUTCOME>
        <OUTCOME>stfl</OUTCOME>
        <PROPERTY> position = (143, 111) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>FC</NAME>
        <OUTCOME>o changed</OUTCOME>
        <OUTCOME>1 changed</OUTCOME>
        <OUTCOME>2 changed</OUTCOME>
        <OUTCOME>3 changed</OUTCOME>
        <PROPERTY> position = (288, 280) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>Besthand</NAME>
        <OUTCOME>myhand</OUTCOME>
        <OUTCOME>opponent</OUTCOME>
        <PROPERTY> position = (49, -17) </PROPERTY>
      </VARIABLE>
      <VARIABLE TYPE="nature">
         <NAME>MH</NAME>
        <OUTCOME>no</OUTCOME>
        <OUTCOME>1 a</OUTCOME>
        <OUTCOME>2 v</OUTCOME>
        <OUTCOME>2 a</OUTCOME>
        <OUTCOME>fl</OUTCOME>
        <OUTCOME>st</OUTCOME>
        <OUTCOME>3 v</OUTCOME>
        <OUTCOME>stfl</OUTCOME>
        <PROPERTY> position = (-23, 112) </PROPERTY>
      </VARIABLE>
      <!-- Probability Distributions -->
      <DEFINITION>
        <FOR>SC</FOR>
        <GIVEN>OH1</GIVEN>
        <TABLE>0.0 0.0 0.0 0.0 0.0 1.0 1.0 1.0 1.0 0.0 0.0 1.0 1.0 1.0 0.0 0.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0</TABLE>
      </DEFINITION>
      <DEFINITION>
        <FOR>OH0</FOR>
        <TABLE>0.1672 0.0445 0.0635 0.4659 0.1694 0.0494 0.0353 0.0024 0.0024</TABLE>
      </DEFINITION>
      <DEFINITION>
        <FOR>OH1</FOR>
        <GIVEN>FC</GIVEN>
        <GIVEN>OH0</GIVEN>
        <TABLE>1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 0.1583 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.1814 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0534 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.347 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0681 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0635 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.3674 0.6224 0.0 0.0 1.0 0.0 0.0 0.0 0.4796 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.4659 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.1224 0.1224 0.9592 0.0 0.0 1.0 0.0 0.0 0.1738 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.1694 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.2143 0.0 0.0 0.0 0.0 0.5 0.0 0.0536 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0494 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.1632 0.0307 0.0 0.0 0.0 0.0 0.5 0.0 0.0383 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0353 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0408 0.0 0.0 0.0 0.0 0.0 0.0026 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0024 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0102 0.0 0.0 0.0 0.0 0.0 0.0 0.0026 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0024 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0</TABLE>
      </DEFINITION>
      <DEFINITION>
        <FOR>OH2</FOR>
        <GIVEN>SC</GIVEN>
        <GIVEN>OH1</GIVEN>
        <TABLE>1.0 0.0 1.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.5903 0.5121 0.0 0.0 0.0 0.0 0.0 0.5613 0.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.1181 0.1024 0.0 0.0 0.0 0.0 0.0 0.157 0.7183 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.9231 0.0 0.0 0.0 0.0 0.0 0.0 0.1154 0.1154 0.8838 0.0 0.0 0.0 0.0 0.1757 0.0667 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0769 0.0 0.0 0.0 0.0 0.0 0.0 0.0096 0.0096 0.0736 0.0 0.0 0.0 0.0 0.0055 0.1145 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.2188 0.0 1.0 0.0 0.0 0.0 0.0559 0.0559 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.1666 0.0313 0.0 0.0 1.0 0.0 0.0 0.0392 0.0392 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0426 0.0 0.0 1.0 0.0 0.0027 0.0027 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0104 0.0 0.0 0.0 0.0 1.0 0.0027 0.0027 0.0 0.0 0.0 0.0 0.0 0.0 0.0</TABLE>
      </DEFINITION>
      <DEFINITION>
        <FOR>FC</FOR>
        <GIVEN>OH0</GIVEN>
        <TABLE>0.0 0.0 0.0 0.0 0.0 1.0 1.0 1.0 1.0 0.0 0.0 1.0 1.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0</TABLE>
      </DEFINITION>
      <DEFINITION>
        <FOR>Besthand</FOR>
        <GIVEN>MH</GIVEN>
        <GIVEN>OH2</GIVEN>
        <TABLE>0.5 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.5 0.0 0.0 0.0 0.0 0.0 0.0 1.0 1.0 0.5 0.0 0.0 0.0 0.0 0.0 1.0 1.0 1.0 0.5 0.0 0.0 0.0 0.0 1.0 1.0 1.0 1.0 0.5 0.0 0.0 0.0 1.0 1.0 1.0 1.0 1.0 0.5 0.0 0.0 1.0 1.0 1.0 1.0 1.0 1.0 0.5 0.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 0.5 0.5 1.0 1.0 1.0 1.0 1.0 1.0 1.0 0.0 0.5 1.0 1.0 1.0 1.0 1.0 1.0 0.0 0.0 0.5 1.0 1.0 1.0 1.0 1.0 0.0 0.0 0.0 0.5 1.0 1.0 1.0 1.0 0.0 0.0 0.0 0.0 0.5 1.0 1.0 1.0 0.0 0.0 0.0 0.0 0.0 0.5 1.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.5 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.5</TABLE>
      </DEFINITION>
      <DEFINITION>
        <FOR>MH</FOR>
        <TABLE>0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125</TABLE>
      </DEFINITION>
  </NETWORK>
</BIF>
